import { Inter } from "next/font/google";
import "../styles/index.scss";
import { Footer, Navbar } from "@/shared/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next JS + Sanity",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
