import { Inter, Roboto } from "next/font/google";
import "../styles/index.scss";
import { Footer, Navbar } from "@/shared/components";
import { MantineProvider, createTheme, ColorSchemeScript } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  colorScheme: "dark",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <MantineProvider theme={theme}>
            <Navbar/>
            {children}
            <Footer/>
          </MantineProvider>
        </body>
      </html>
  );
}
