import { Inter, Roboto } from "next/font/google";
import { Footer, Navbar } from "@/shared/components";
import { client } from "@/utils/sanity";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <main>
      {children}
    </main>
  );
}